language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t kaitingpeck/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true kaitingpeck/react-test npm test

after_success:
    # use default Dockerfile (production)
    - docker build -t kaitingpeck/multi-client ./client
    - docker build -t kaitingpeck/multi-nginx ./nginx
    - docker build -t kaitingpeck/multi-server ./server
    - docker build -t kaitingpeck/multi-worker ./worker
    
    # Log in to the docker CLI
    # echo $DOCKER_PASSWORD - retrieve DOCKER_PASSWORD from environment variable and emit that over stdin
    # and input to the next command (on the other side of the pipe - |)
    # i.e., emitted to the stdin channel for the next command
    # tell 'docker login' it can expect to receive the password over stdin
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to docker hub
    - docker push kaitingpeck/multi-client
    - docker push kaitingpeck/multi-nginx
    - docker push kaitingpeck/multi-server
    - docker push kaitingpeck/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-1
    app: multi-docker
    env: MultiDocker-env
    # travis zips us project and puts it in the S3 bucket
    bucket_name: elasticbeanstalk-us-east-1-199166987708
    bucket_path: 'docker-multi'
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY